export default function getTableObject(
  number,
  label,
  balance,
  starkgate,
  volume,
  txs,
  fee,
  activity,
  witm,
  domain,
  address,
  transactions,
  contracts,
  result,
) {
  return {
    number,
    label,
    balance: balance.total,
    starkgate,
    volume,
    txs,
    fee,
    contractsCount: activity.contractActivity,
    mwd: `${activity.monthActivity}/${activity.weekActivity}/${activity.dayActivity}`,
    witm,
    domain,
    collapse: {
      address,
      balance: balance.tokens,
      transactions,
      contracts,
    },
    result,
  };
}
